config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :static_pages
  end
  match '*path', :to => 'static_pages#show', :via => :all, :constraints => lambda{|req|
    !req.path.start_with?('/assets')
  }
  get ':prefix/:page', :to => 'static_pages#show', :as => :static_page, :constraints => lambda{|req|
    !req.path.start_with?('/assets')
  }
  root 'static_pages#show'
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < ApplicationController

  before_action do
    if(params[:product_id])
      @product = Product.find_by_id(params[:product_id])
      @pages = @product.static_pages_dataset
    else
      @pages = StaticPage.dataset
    end
    @pages = @pages.order(:title)
    @page = @pages.where(:id => params[:id]).first
  end

  def index
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to admin_static_pages_path
      end
      format.html do
        unless(@product)
          @pages = Hash[
            Product.dataset.order(:name).all.map do |product|
              [product, product.static_pages]
            end
          ]
        else
          @pages = @pages.all.group_by do |page|
            page.product
          end
        end
      end
    end
  end

  def show
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to admin_static_pages_path
      end
      format.html do
        unless(@page)
          flash[:error] = 'Failed to locate requested page!'
          redirect_to admin_static_pages_path
        end
      end
    end
  end

  def new
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to admin_static_pages_path
      end
      format.html do
        @products = Product.all
      end
    end
  end

  def create
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to admin_static_pages_path
      end
      format.html do
        args = Hash[
          params.find_all do |k,v|
            k.to_s.start_with?('page_')
          end.map do |k,v|
            [k.sub('page_', ''), v]
          end
        ].with_indifferent_access
        @product = Product.find_by_id(args.delete(:product_id))
        if(@product)
          begin
            @page = @product.add_static_page(args)
            flash[:success] = "Page created! (#{@product.name}: #{@page.path})"
          rescue => e
            puts "ERROR!!!: #{e}"
            flash[:error] = "Failed to create path: #{e}"
          end
        end
        redirect_to admin_static_pages_path
      end
    end
  end

  def edit
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to admin_static_pages_path
      end
      format.html do
        unless(@page)
          flash[:error] = "Failed to find requested page (#{params[:id]})"
          redirect_to admin_static_pages_path
        end
        @products = Product.all
      end
    end
  end

  def update
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to admin_static_pages_path
      end
      format.html do
        if(@page)
          args = Hash[
            params.find_all do |k,v|
              k.to_s.start_with?('page_')
            end.map do |k,v|
              [k.sub('page_', ''), v]
            end
          ].with_indifferent_access
          begin
            @page.update(args)
            @page.save
            flash[:success] = "Page updated! (#{@product.name}: #{@page.path})"
          rescue => e
            flash[:error] = "Failed to create path: #{e}"
          end
        else
          flash[:error] = 'Failed to find requested page!'
        end
        redirect_to admin_static_pages_path
      end
    end
  end

  def destroy
    begin
      if(@page.destroy)
        flash[:success] = "Page has been deleted (#{@page.path})"
      else
        flash[:error] = "Failed to delete page (#{@page.path})"
      end
    rescue => e
      flash[:error] = "Failed to delete page (#{@page.path}): #{e}"
    end
    respond_to do |format|
      format.js do
        javascript_redirect_to admin_static_pages_path
      end
      format.html do
        redirect_to admin_static_pages_path
      end
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_action :validate_user!, :except => [:show, :deliver_asset]
  before_action :validate_access!, :except => [:show, :deliver_asset]

  before_action do
    if(@product)
      product, path = params[:path].to_s.split('/', 2)
      if(@product.internal_name == product)
        params[:path] = path
      end
    else
      product, path = params[:path].to_s.split('/', 2)
      if(product && product.present?)
        @product = Product.find_by_internal_name(product)
      end
      unless(@product)
        @product = Product.find_by_internal_name('fission')
      else
        params[:path] = path
      end
    end
  end

  def show
    respond_to do |format|
      format.js do
        not_found!
      end
      format.html do
        if(@product)
          path = params[:path].present? ? params[:path] : 'index'
          unless(static_file_path(@product, path))
            @page = @product.static_pages_dataset.where(:path => path).first
            unless(@page)
              not_found!
            else
              if(@page.redirect_url)
                redirect_to @page.redirect_url
              else
                content_for(:title, @page.title)
              end
            end
          end
        else
          not_found!
        end
      end
    end
  end

  def static_file_path(product, page)
    data = Rails.application.config.settings.get(:static, :pages, product.internal_name, page)
    if(data)
      @app_name = product.name
      @data = data
      if(data.first.delete(:navigation))
        @nav_partial = Smash.new(
          :partial => 'static/nav',
          :locals => Smash.new(
            :nav => data.shift
          )
        )
      end
      @site_style = 'fission-app-static'
      render 'static/display'
      true
    end
  end

end

app/views/admin/static_pages/_form.html.haml
:ruby
  if(defined?(page) && page)
    title = "Update static page ID: #{page.id}"
    url = admin_static_page_path(page.id)
    method = :put
    button_text = 'Update'
    page = page.values
  else
    title = 'Create new static page'
    url = admin_static_pages_path
    method = :post
    button_text = 'Create'
    page = {}
  end
%div.panel.panel-default
  %div.panel-heading
    %h4= title
  %div.panel-body
    = form_tag url, :method => method do
      %div.form-group
        = label_tag(:page_product_id)
        = select_tag(:page_product_id, options_for_select(Hash[products.map{|p| [p.name, p.id]}], page.fetch(:product_id, params[:product_id])), :class => 'form-control')
      %div.from-group
        = label_tag(:page_redirect_url)
        = text_field_tag :page_redirect_url, page[:redirect_url], :class => 'form-control'
      %div.form-group
        = label_tag(:page_title)
        = text_field_tag :page_title, page[:title], :class => 'form-control'
      %div.form-group
        = label_tag(:page_path)
        = text_field_tag :page_path, page[:path], :class => 'form-control'
      %div.form-group
        = label_tag(:page_style)
        = text_field_tag :page_style, page[:style], :class => 'form-control'
      %div.form-group
        = label_tag(:page_content)
        = text_area_tag :page_content, page[:content], :class => 'form-control'
      = submit_tag button_text, :class => 'btn btn-success'

app/views/admin/static_pages/_list.html.haml
- pages.each do |product, product_pages|
  %div.panel.panel-default
    %div.panel-heading
      %span.pull-right= link_to 'Create', new_admin_static_page_path(:product_id => product.id), :class => 'btn btn-success'
      %span
        %h4= product.name
    %div.clearfix
    %div.panel-body
      %table.table.table-hover
        %thead
          %tr
            %th.col-md-3
              Title
            %th.col-md-3
              Path
            %th.col-md-5
              Updated
            %th.col-md-1
        %tbody
          - product_pages.each do |page|
            %tr
              %td= page.title
              %td= page.path
              %td= page.updated_at
              %td
                %a{:href => admin_static_page_path(page.id)}
                  %span.glyphicon.glyphicon-zoom-in
                %a{:href => edit_admin_static_page_path(page.id)}
                  %span.glyphicon.glyphicon-cog
                %a.window-rails{:href => '#', 'window-rails-ajax' => :delete, 'window-rails-url' => admin_static_page_path(page.id), 'window-rails-confirm' => "Destroy static page (#{page.title})?", 'window-rails-title' => 'Static page destruction'}
                  %span.glyphicon.glyphicon-remove

app/views/admin/static_pages/edit.html.haml
%div#fission-static-page-edit.container.container-padding
  = render :partial => 'admin/static_pages/form', :locals => {:page => @page, :products => @products}

app/views/admin/static_pages/index.html.haml
%div#fission-static-pages.container.container-padding
  = render :partial => 'admin/static_pages/list', :locals => {:pages => @pages}

app/views/admin/static_pages/new.html.haml
%div#fission-static-page-new.container.container-padding
  = render :partial => 'admin/static_pages/form', :locals => {:products => @products}

app/views/admin/static_pages/show.html.haml
%div#fission-static-page.container.container-padding
  %div.panel.panel-default
    %div.panel-heading
      %h4= "Static page ID #{@page.id}"
    %div.panel-body
      %table.table
        %thead
          %tr.info
            %th{:colspan => 2}
              Page details
        %tbody
          %tr
            %td.col-md-3
              %b
                Product
            %td= @page.product.name
          %tr
            %td.col-md-3
              %b
                Title
            %td= @page.title
          %tr
            %td.col-md-3
              %b
                Path
            %td= @page.path
      %div.well.well-sm
        %pre= @page.content

app/views/static_pages/show.html.haml
:ruby
  content_for(:container) do
    @page.content.md_to_html
  end

= render 'layouts/container'